### ISSUE TITLE
Add a place to manage repo secrets

### ISSUE THREAD

**Issue by kneal** [go-vela/ui#103]
## Description

_What is your idea?_

Provide users a place to manage their secrets in the UI.

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

Users do not have to download the CLI or interact with the API to manage secrets

## Definition of Done

_What is the end goal of this story?_

Secrets manage is available

**Comment by davidvader** [comment]
Implemented repo secrets at `org/repo/settings/secrets`.
This triggered conversation on where to put org/shared secrets, *WIP*

**Comment by wass3r** [comment]
added in #146
