### ISSUE TITLE
Colorize log output

### ISSUE THREAD

**Issue by wass3r** [go-vela/ui#141]
## Description

Log output that contains ANSI control sequence to colorize text is unhandled resulting in them being rendered as-is. Let's convert them and treat affected output respectively.

## Value

Cleaner log output

## Definition of Done

Control characters/escape sequences are converted to respective color. In addition, colors are accessible for currently supported themes.

## Effort  (Optional)

1-2 days

## Impacted Personas (Optional)

Log output viewers :)

**Comment by DavidTNguyen** [comment]
I think this has a huge impact to the readability of the test execution results.  Drone tells me exactly which one of my tests failed/passed, while Vela kinda does, but I have to sip through a massive amount of unintelligible text.

- Vela

![Vela](https://user-images.githubusercontent.com/11265859/79393227-871ee100-7f3a-11ea-860d-0b06e9753835.png)

- Drone

![Drone](https://user-images.githubusercontent.com/11265859/79393230-88500e00-7f3a-11ea-8d6d-d5b230ee44bf.png)

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ go-vela/community.

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
